### ISSUE TITLE
Fertig vorkunfigurierte Einheiten

### ISSUE THREAD

**Issue by Montiemedia** [CTF-A3/CTF_Mods#2]
Schön wären vordefinierte Einheiten, wie damals in unserem 1st Core! Damit wir unsere Missionen standardisieren können :)

BW - Tropen/Fleck (BW Kleiderkammer)
US Army - UCP/OCP
US Marines - MARPAT
Russen - Wasuaimmerdiehaben

Feature Request :)

**Comment by flaver12** [comment]
Gibts bald als comp braucheb wir nicht im mod
